from dataclasses import dataclass

from app.core.errors import TopicNotFoundError
from app.topics import (
    algebraic_fractions,
    algebraic_indices,
    algebraic_proof,
    angles,
    area_perimeter,
    best_buys,
    changing_subject,
    charts,
    circle_theorems,
    classify_expressions,
    compound_measures,
    cumulative_frequency,
    data_handling,
    decimals,
    estimation,
    expand_factorise,
    forming_equations,
    fractions,
    functions,
    graphs,
    histograms,
    inequalities,
    inequalities_number_line,
    iteration,
    linear_equations,
    negative_numbers,
    number_theory,
    order_of_operations,
    percentages,
    powers_roots,
    probability,
    proportion,
    pythagoras,
    quadratic_equations,
    quadratic_graphs,
    ratio,
    sequences,
    simultaneous_equations,
    standard_form,
    tree_diagrams,
    triangle_rules,
    trigonometry,
    vectors,
    venn_diagrams,
)
from app.topics import statistics as statistics_topics
from app.topics.base import TopicDefinition

SECTIONS: list[tuple[str, str]] = [
    ("number", "Number"),
    ("algebra", "Algebra"),
    ("ratio_proportion", "Ratio & Proportion"),
    ("geometry", "Geometry"),
    ("probability", "Probability"),
    ("statistics", "Statistics"),
]

_TOPIC_LIST: list[TopicDefinition] = [
    # Number
    fractions.TOPIC_SIMPLIFY,
    fractions.TOPIC_EQUIVALENT,
    fractions.TOPIC_ORDERING,
    fractions.TOPIC_ADD_SUBTRACT,
    fractions.TOPIC_MULTIPLY,
    fractions.TOPIC_DIVIDE,
    fractions.TOPIC_DIVIDE_FOUNDATION,
    fractions.TOPIC_MIXED_NUMBER_ARITHMETIC,
    fractions.TOPIC_IMPROPER_MIXED,
    fractions.TOPIC_OF_AMOUNT,
    decimals.TOPIC_ROUND_DP,
    decimals.TOPIC_ROUND_SF,
    decimals.TOPIC_ORDERING,
    decimals.TOPIC_ADD_SUBTRACT,
    decimals.TOPIC_MULTIPLY,
    decimals.TOPIC_DIVIDE,
    decimals.TOPIC_RECURRING_SINGLE_DIGIT,
    decimals.TOPIC_RECURRING_TWO_DIGIT,
    decimals.TOPIC_RECURRING_TO_FRACTION,
    order_of_operations.TOPIC_BIDMAS,
    standard_form.TOPIC_TO_STANDARD_FORM,
    standard_form.TOPIC_TO_STANDARD_FORM_SMALL,
    standard_form.TOPIC_FROM_STANDARD_FORM_LARGE,
    standard_form.TOPIC_FROM_STANDARD_FORM_SMALL,
    standard_form.TOPIC_MULTIPLY_DIVIDE,
    standard_form.TOPIC_MULTIPLY_DIVIDE_FOUNDATION,
    standard_form.TOPIC_ADD_SUBTRACT,
    standard_form.TOPIC_CALCULATOR,
    estimation.TOPIC_ESTIMATION,
    estimation.TOPIC_ERROR_INTERVAL,
    estimation.TOPIC_BOUNDS,
    negative_numbers.TOPIC_NEGATIVE_ADD_SUBTRACT,
    negative_numbers.TOPIC_NEGATIVE_MULTIPLY_DIVIDE,
    negative_numbers.TOPIC_NEGATIVE_ORDERING,
    decimals.TOPIC_POWERS_OF_TEN,
    number_theory.TOPIC_PRIME_NUMBERS,
    number_theory.TOPIC_MULTIPLES,
    number_theory.TOPIC_FACTORS,
    number_theory.TOPIC_PRIME_FACTORS_FOUNDATION,
    number_theory.TOPIC_PRIME_FACTORS_HIGHER,
    number_theory.TOPIC_LCM_BY_LISTING,
    number_theory.TOPIC_HCF_BY_LISTING,
    number_theory.TOPIC_HCF_LCM_BY_PRIME_FACTORS,
    powers_roots.TOPIC_POWERS_FOUNDATION,
    powers_roots.TOPIC_NEGATIVE_INDICES,
    powers_roots.TOPIC_POWERS_HIGHER,
    powers_roots.TOPIC_SIMPLIFYING_INDICES_CHALLENGING,
    powers_roots.TOPIC_INDICES_COMMON_BASE_EQUATIONS,
    powers_roots.TOPIC_ROOTS_FOUNDATION,
    powers_roots.TOPIC_ROOTS_HIGHER,
    powers_roots.TOPIC_SURDS_MULTIPLY_DIVIDE,
    powers_roots.TOPIC_ALGEBRAIC_SURDS,
    powers_roots.TOPIC_RATIONALISE_DENOMINATOR,
    # Algebra
    classify_expressions.TOPIC_CLASSIFY_EXPRESSIONS,
    linear_equations.TOPIC_ONE_STEP,
    linear_equations.TOPIC_TWO_STEP,
    linear_equations.TOPIC_MULTI_STEP,
    linear_equations.TOPIC_BOTH_SIDES_FOUNDATION,
    linear_equations.TOPIC_BOTH_SIDES,
    linear_equations.TOPIC_BRACKETS_FOUNDATION,
    linear_equations.TOPIC_BRACKETS,
    forming_equations.TOPIC_FORMING_EQUATIONS_FOUNDATION,
    forming_equations.TOPIC_FORMING_EQUATIONS_HIGHER,
    changing_subject.TOPIC_CHANGE_SUBJECT_FOUNDATION,
    changing_subject.TOPIC_CHANGE_SUBJECT_HIGHER,
    expand_factorise.TOPIC_EXPAND_SINGLE,
    expand_factorise.TOPIC_EXPAND_DOUBLE_FOUNDATION,
    expand_factorise.TOPIC_EXPAND_DOUBLE,
    expand_factorise.TOPIC_EXPAND_TRIPLE,
    expand_factorise.TOPIC_FACTORISE_COMMON,
    expand_factorise.TOPIC_FACTORISE_QUADRATIC_FOUNDATION,
    expand_factorise.TOPIC_FACTORISE_QUADRATIC,
    algebraic_indices.TOPIC_ALGEBRAIC_INDICES_FOUNDATION,
    algebraic_indices.TOPIC_ALGEBRAIC_INDICES_HIGHER,
    quadratic_graphs.TOPIC_COMPLETING_THE_SQUARE,
    quadratic_graphs.TOPIC_TURNING_POINT,
    quadratic_equations.TOPIC_QUADRATIC_FORMULA,
    functions.TOPIC_FUNCTIONS_EVALUATE,
    functions.TOPIC_FUNCTIONS_COMPOSITE_INVERSE,
    algebraic_fractions.TOPIC_ALGEBRAIC_FRACTIONS_ADD_SUBTRACT,
    algebraic_fractions.TOPIC_ALGEBRAIC_FRACTIONS_MULTIPLY_DIVIDE,
    simultaneous_equations.TOPIC_COMMON_COEFFICIENT,
    simultaneous_equations.TOPIC_DIFFERENT_COEFFICIENT,
    simultaneous_equations.TOPIC_FORMING_AND_SOLVING,
    simultaneous_equations.TOPIC_QUADRATIC,
    simultaneous_equations.TOPIC_GRAPHICALLY,
    inequalities.TOPIC_SOLVING_INEQUALITIES_FOUNDATION,
    inequalities.TOPIC_SOLVING_INEQUALITIES_HIGHER,
    inequalities.TOPIC_SATISFYING_INEQUALITIES_FOUNDATION,
    inequalities.TOPIC_SATISFYING_INEQUALITIES_HIGHER,
    inequalities.TOPIC_QUADRATIC_INEQUALITIES,
    inequalities_number_line.TOPIC_INEQUALITIES_NUMBER_LINE_FOUNDATION,
    inequalities_number_line.TOPIC_INEQUALITIES_NUMBER_LINE_HIGHER,
    algebraic_proof.TOPIC_ALGEBRAIC_PROOF,
    sequences.TOPIC_NEXT_TERM,
    sequences.TOPIC_TERM_TO_TERM_RULE,
    sequences.TOPIC_NTH_TERM,
    sequences.TOPIC_QUADRATIC_NTH_TERM,
    iteration.TOPIC_ITERATION,
    graphs.TOPIC_PLOT_STRAIGHT_LINE,
    graphs.TOPIC_PLOT_QUADRATIC,
    graphs.TOPIC_PLOT_CUBIC,
    graphs.TOPIC_PLOT_RECIPROCAL,
    graphs.TOPIC_PLOT_DISTANCE_TIME,
    graphs.TOPIC_LINE_EQUATION_FROM_GRAPH,
    graphs.TOPIC_PARALLEL_LINES_EQUATION,
    graphs.TOPIC_PERPENDICULAR_LINES_EQUATION,
    graphs.TOPIC_DISTANCE_TIME_INTERPRET,
    graphs.TOPIC_VELOCITY_TIME_INTERPRET,
    graphs.TOPIC_GRAPH_TRANSFORMATIONS,
    # Ratio & Proportion
    percentages.TOPIC_OF_AMOUNT,
    percentages.TOPIC_CHANGE,
    percentages.TOPIC_FIND_PERCENTAGE_CHANGE,
    percentages.TOPIC_PERCENTAGE_INCREASE_DECREASE_CALCULATOR,
    percentages.TOPIC_REVERSE_FOUNDATION,
    percentages.TOPIC_REVERSE,
    percentages.TOPIC_COMPOUND,
    percentages.TOPIC_COMPOUND_FOUNDATION,
    percentages.TOPIC_SIMPLE_INTEREST,
    percentages.TOPIC_MIXED_PERCENTAGES,
    best_buys.TOPIC_BEST_BUYS,
    ratio.TOPIC_SHARE_TWO,
    ratio.TOPIC_FIND_SHARE,
    ratio.TOPIC_SHARE_THREE,
    ratio.TOPIC_SHARE_THREE_FOUNDATION,
    ratio.TOPIC_COMBINE,
    ratio.TOPIC_RATIO_1_TO_N,
    ratio.TOPIC_RATIO_DIFFERENCE,
    ratio.TOPIC_RATIO_DIFFERENCE_HIGHER,
    ratio.TOPIC_RATIO_TO_EQUATION,
    ratio.TOPIC_RATIO_SHAPE_SIMILAR_FOUNDATION,
    ratio.TOPIC_RATIO_SHAPE_SIMILAR_HIGHER,
    proportion.TOPIC_DIRECT_PROPORTION,
    proportion.TOPIC_INVERSE_PROPORTION,
    proportion.TOPIC_ALGEBRAIC_DIRECT_PROPORTION,
    proportion.TOPIC_ALGEBRAIC_INVERSE_PROPORTION,
    compound_measures.TOPIC_SDT_MIXED,
    compound_measures.TOPIC_SPEED_WITH_CONVERSIONS,
    compound_measures.TOPIC_UNIT_CONVERSIONS,
    compound_measures.TOPIC_UNIT_CONVERSIONS_HIGHER,
    compound_measures.TOPIC_DENSITY,
    compound_measures.TOPIC_DENSITY_HIGHER,
    compound_measures.TOPIC_PRESSURE,
    compound_measures.TOPIC_PRESSURE_HIGHER,
    # Geometry
    area_perimeter.TOPIC_RECTANGLE,
    area_perimeter.TOPIC_TRIANGLE,
    area_perimeter.TOPIC_COMPOSITE_RECTANGLES,
    area_perimeter.TOPIC_CIRCLE_FOUNDATION,
    area_perimeter.TOPIC_CIRCLE,
    area_perimeter.TOPIC_SEMICIRCLE_COMPOUND,
    area_perimeter.TOPIC_SEMICIRCLE_COMPOUND_HIGHER,
    area_perimeter.TOPIC_SUBTRACT_COMPOUND,
    area_perimeter.TOPIC_SUBTRACT_COMPOUND_FOUNDATION,
    angles.TOPIC_STRAIGHT_LINE,
    angles.TOPIC_STRAIGHT_LINE_HIGHER,
    angles.TOPIC_AROUND_POINT,
    angles.TOPIC_AROUND_POINT_HIGHER,
    angles.TOPIC_TRIANGLE,
    angles.TOPIC_TRIANGLE_HIGHER,
    angles.TOPIC_PARALLEL_LINES_FOUNDATION,
    angles.TOPIC_PARALLEL_LINES,
    angles.TOPIC_EXTERIOR_FOUNDATION,
    angles.TOPIC_EXTERIOR,
    angles.TOPIC_POLYGON_INTERIOR_FOUNDATION,
    angles.TOPIC_POLYGON_INTERIOR,
    pythagoras.TOPIC_HYPOTENUSE_TRIPLE,
    pythagoras.TOPIC_HYPOTENUSE_DECIMAL,
    pythagoras.TOPIC_SHORTER_LEG,
    pythagoras.TOPIC_SURD_HYPOTENUSE,
    pythagoras.TOPIC_LADDER_CONTEXT,
    pythagoras.TOPIC_LADDER_CONTEXT_FOUNDATION,
    trigonometry.TOPIC_MISSING_SIDE_FOUNDATION,
    trigonometry.TOPIC_MISSING_SIDE_HIGHER,
    trigonometry.TOPIC_MISSING_ANGLE_FOUNDATION,
    trigonometry.TOPIC_MISSING_ANGLE_HIGHER,
    trigonometry.TOPIC_MIXED,
    triangle_rules.TOPIC_SINE_RULE,
    triangle_rules.TOPIC_COSINE_RULE,
    triangle_rules.TOPIC_TRIANGLE_AREA,
    vectors.TOPIC_VECTORS_ARITHMETIC_FOUNDATION,
    vectors.TOPIC_VECTORS_ARITHMETIC_HIGHER,
    vectors.TOPIC_GEOMETRIC_VECTORS,
    circle_theorems.TOPIC_CIRCLE_THEOREMS,
    # Probability
    probability.TOPIC_SINGLE_EVENT,
    probability.TOPIC_COMPLEMENT,
    probability.TOPIC_COMBINED_DICE,
    probability.TOPIC_CONDITIONAL,
    probability.TOPIC_LISTING_OUTCOMES,
    probability.TOPIC_AND_OR_RULE,
    probability.TOPIC_EXPECTATION,
    tree_diagrams.TOPIC_TREE_INDEPENDENT,
    tree_diagrams.TOPIC_TREE_DEPENDENT,
    tree_diagrams.TOPIC_TREE_DRAWING,
    tree_diagrams.TOPIC_TREE_ALGEBRAIC,
    tree_diagrams.TOPIC_TREE_MIXED,
    data_handling.TOPIC_SET_NOTATION,
    data_handling.TOPIC_SET_NOTATION_FOUNDATION,
    data_handling.TOPIC_PRODUCT_RULE_COUNTING,
    data_handling.TOPIC_RELATIVE_FREQUENCY,
    data_handling.TOPIC_TWO_WAY_TABLES,
    data_handling.TOPIC_SAMPLE_SPACE_DIAGRAMS,
    venn_diagrams.TOPIC_VENN_SHADING,
    venn_diagrams.TOPIC_VENN_PROBABILITY,
    venn_diagrams.TOPIC_VENN_NOTATION,
    venn_diagrams.TOPIC_VENN_ALGEBRA,
    # Statistics
    statistics_topics.TOPIC_MEAN,
    statistics_topics.TOPIC_MODE,
    statistics_topics.TOPIC_MEDIAN,
    statistics_topics.TOPIC_RANGE,
    statistics_topics.TOPIC_AVERAGES_COMBINED,
    statistics_topics.TOPIC_INTERQUARTILE_RANGE,
    statistics_topics.TOPIC_MEAN_FREQUENCY_TABLE,
    statistics_topics.TOPIC_MEAN_GROUPED_FREQUENCY_TABLE,
    statistics_topics.TOPIC_MEAN_GROUPED_FREQUENCY_TABLE_FOUNDATION,
    statistics_topics.TOPIC_MODE_FREQUENCY_TABLE,
    statistics_topics.TOPIC_MEDIAN_FREQUENCY_TABLE,
    statistics_topics.TOPIC_RANGE_FREQUENCY_TABLE,
    statistics_topics.TOPIC_REVERSE_MEAN,
    statistics_topics.TOPIC_REVERSE_MEAN_FOUNDATION,
    charts.TOPIC_BAR_CONSTRUCT,
    charts.TOPIC_BAR_INTERPRET,
    charts.TOPIC_COMPOSITE_BAR,
    charts.TOPIC_PIE_CONSTRUCT,
    charts.TOPIC_PIE_INTERPRET,
    charts.TOPIC_TIME_SERIES,
    cumulative_frequency.TOPIC_CUMULATIVE_FREQUENCY_PLOT,
    cumulative_frequency.TOPIC_CUMULATIVE_FREQUENCY_INTERPRET,
    cumulative_frequency.TOPIC_BOX_PLOT_CONSTRUCT,
    cumulative_frequency.TOPIC_BOX_PLOT_INTERPRET,
    histograms.TOPIC_HISTOGRAM_PLOT,
    histograms.TOPIC_HISTOGRAM_INTERPRET,
]

TOPICS: dict[str, TopicDefinition] = {t.id: t for t in _TOPIC_LIST}


def get_topic(topic_id: str) -> TopicDefinition:
    try:
        return TOPICS[topic_id]
    except KeyError:
        raise TopicNotFoundError(topic_id) from None


def list_topics() -> list[TopicDefinition]:
    return list(_TOPIC_LIST)


@dataclass(frozen=True)
class GroupNode:
    name: str
    topics: tuple[TopicDefinition, ...]


@dataclass(frozen=True)
class SectionNode:
    id: str
    name: str
    groups: tuple[GroupNode, ...]


def sections_tree() -> list[SectionNode]:
    """Group all topics by section then by group, preserving the declared
    order in SECTIONS and _TOPIC_LIST (not alphabetical). Sections with no
    topics yet (e.g. Number) are still included, with an empty groups tuple.
    """
    nodes: list[SectionNode] = []
    for section_id, section_name in SECTIONS:
        section_topics = [t for t in _TOPIC_LIST if t.section == section_id]

        group_order: list[str] = []
        group_topics: dict[str, list[TopicDefinition]] = {}
        for t in section_topics:
            if t.group not in group_topics:
                group_topics[t.group] = []
                group_order.append(t.group)
            group_topics[t.group].append(t)

        groups = tuple(GroupNode(name=g, topics=tuple(group_topics[g])) for g in group_order)
        nodes.append(SectionNode(id=section_id, name=section_name, groups=groups))
    return nodes
